name: Deploy to Server
on:
  push:
    branches:
      - '*'
    branches-ignore:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Copy files to server
        run: |
          cp test_file_1.py $HOME/test_file_1.py    
          cp test_file_2.py $HOME/test_file_2.py