name: Test Action 2
on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Log GitHub Context
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Ref Name: ${{ github.ref_name }}"
          echo "Repository: ${{ github.repository }}"

      - name: Copy files to server
        run: |
          cp test_file_1.py $HOME/test_file_1.py    
          cp test_file_2.py $HOME/test_file_2.py

