name: Test Action
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout configuration branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - run: echo "Triggered on branch ${{ github.ref }}"
