name: Test Action
on:
  push: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout configuration branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT}}
          ref: main

      - run: echo "Triggered on branch ${{ github.ref }}"
