name: Test Action
on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout configuration branch
        uses: actions/checkout@v2
        with:
          GITHUB_TOKEN: ${{ secrets.PAT}}
          ref: main

      - run: echo "Triggered on branch ${{ github.ref }}"
