name: Deploy to Server
on:
#  push:
#    branches:
#      - test
#      - test_2
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Copy files to server
        run: |
          cp test_file_1.py $HOME/test_file_1.py    
          cp test_file_2.py $HOME/test_file_2.py