name: Test Action
on:
  push: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout configuration branch
        uses: actions/checkout@v1
        with:
          ref: main
          persist-credentials: false

      - run: echo "Triggered on branch ${{ github.ref }}"
