name: Test Action
on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout configuration branch
        uses: actions/checkout@v2
        with:
          ref: main
          persist-credentials: false

      - run: echo "Triggered on branch ${{ github.ref }}"
